version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment: 
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pumpkin
      - MYSQL_DATABASE=shipmint


