CREATE TABLE users (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) DEFAULT NULL,
    `createdAt` DATETIME DEFAULT NULL,
    `updatedAt` DATETIME DEFAULT NULL
);