CREATE TABLE users (
    `id` BIGINT(20) UNSIGNED NOT NULL PRIMARY KEY,
    `name` VARCHAR(255) DEFAULT NULL,
    `email` VARCHAR(255) DEFAULT NULL,
    `googleId` VARCHAR(255) DEFAULT NULL,
    `createdAt` DATETIME DEFAULT NULL,
    `updatedAt` DATETIME DEFAULT NULL
);